# Generated by Django 4.2 on 2023-05-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='slider_01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=70)),
                ('bottom_title', models.CharField(max_length=170)),
                ('botton_text', models.CharField(max_length=170)),
                ('bottom_url', models.CharField(max_length=170)),
                ('phone_no', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
