# Generated by Django 4.2 on 2023-05-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_slider_01_delete_service_delete_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services_01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='services/')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
