# Generated by Django 4.2 on 2023-05-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_services_01'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('project_no', models.CharField(max_length=20)),
                ('project_dese', models.CharField(max_length=30)),
            ],
        ),
    ]
